name: Run IP Get Script and Push README

on:
  push:
    branches:
      - main

jobs:
  run-ip-get:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install requests 
    - name: Run ip_get.py
      run: python .github/workflows/ip_get.py
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.CF }}
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add README.md
        git commit -m "Update README.md with new IP addresses"
        git push origin main