name: Run IP Get Script and Push README

on:
  push:
    branches:
      - main

jobs:
  run-ip-get:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install requests
    - name: Run ip_get.py
      run: python .github/workflows/ip_get.py
    - name: Commit and push changes
      env:
        # 从 GitHub Secrets 中获取自定义的 PAT
        TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add README.md
        git commit -m "Update README.md with new IP addresses"
        # 使用存储在 secrets 中的 PAT 进行认证和 push 操作
        git push https://${TOKEN}@github.com/return2002o/cf-ip.git main